### ISSUE TITLE
Option to show hidden windows

### ISSUE THREAD

**Issue by ghost** [numist/Switch#130]
The normal app switcher (Cmd+Tab) shows all main open windows, even when some windows are hidden. Switch could mimic this.

**Comment by numist** [comment]
This was an intentional design decision—people who use Spaces a lot tend to have so many windows that the interface is overwhelmed when all windows are shown in the window list. The system behaviour of switching Spaces in response to the application switcher has also been the subject of a lot of foul language in the past.

No reason why it couldn't exist sometime behind a checkbox in the preferences, though.

**Comment by ghost** [comment]
I see what you mean and it makes sense. The reason I suggested is that I don't use Spaces at all. I use a sort of Single Application Mode, provided by Isolator, and I never use more than 4/5 apps at a time.
You can keep this one low-priority.

**Comment by numist** [comment]
Isolator is hiding the applications, not minimizing? Yeah, it might be useful to have multiple levels of distinction for window visibility in Switch, the main question is window content availability and state detection. The public APIs are not nearly as rich as what's available to Dock and the window server 😠

**Comment by ghost** [comment]
> Isolator is hiding the applications, not minimizing?

Exactly.

> The public APIs are not nearly as rich as what's available to Dock and the window server.

Yeah, Apple has a bad habit of dumbing down or not document at all public APIs.
Essentially, my request is about showing all windows like Mission Control does, but without the mess.

**Comment by numist** [comment]
Unfortunately the API that Mission Control uses is not public, which makes this feature—and Switch in general—much more difficult to implement :confused:
