### ISSUE TITLE
Do I need XCode 5 to run? Or just to build?

### ISSUE THREAD

**Issue by swankjesse** [numist/Switch#29]
It isn't running for me, but I'm using XCode 4 something.

**Comment by numist** [comment]
If you downloaded the binary from the [release page](https://github.com/numist/Switch/releases/tag/0.0.1) you'll currently only get an interface on launch if you have Accessibility disabled. Otherwise the application should open and be responsive to hotkeys immediately.

Does Activity Monitor show a Switch process?

**Comment by swankjesse** [comment]
Yes, I get a switch process, but it doesn't work.

**Comment by swankjesse** [comment]
(the accessibility enabler thing didn't appear to work.)

**Comment by swankjesse** [comment]
But quitting and restarting worked! Sweet!

**Comment by numist** [comment]
Very possible that you ran into #19. I need to build some debugging hooks and an interface to monitor Switch to make this stuff easier to diagnose.
