### ISSUE TITLE
On first launch, keybinding didn't take

### ISSUE THREAD

**Issue by kemayo** [numist/Switch#57]
The first time I launched Switch it didn't seem to bind the option-tab shortcut. Quitting it and relaunching made it start working.

I hypothesize this is due to it having to ask for permission to control things, and not setting itself up after that is granted, but I have no evidence.

Only thing in the log until after I relaunched it was:

```
2014-01-05 20:32:36.014 Switch[9504:707] NNAppDelegate.m:51 Launched Switch 0.0.5 (β)
```

**Comment by numist** [comment]
Yup, behaviour has been changing between different versions of Mavericks where event taps are affected in different ways by the Accessibility permissions of the app. #19 is tracking this issue, and it should be fixed in the next update.

Once Accessibility is enabled, quitting Switch (via its preferences window is easiest, accessible from the menu bar item) and relaunching it resolves the issue.

**Comment by numist** [comment]
Looks like this wasn't fixed by 19. This issue should track the problem going forward.

**Comment by numist** [comment]
Ok, I've got a fix. What an unfortunate pain.
