### ISSUE TITLE
Isolator's shield window shows up in Switch window list

### ISSUE THREAD

**Issue by cbowns** [numist/Switch#85]
[Isolator](http://willmore.eu/software/isolator/) shows up in Switch's window list:

![isolator window](https://cloud.githubusercontent.com/assets/474/2845004/be090d66-d091-11e3-9032-d2af15d6652a.png)

[The debug window list (.zip)](http://cl.ly/3D2m1r1D1p1g)

**Comment by numist** [comment]
Here's what the window info dict looks like for the shield:

```
@{
    NNWindowLayer : @0,
    NNWindowName : @"",
    NNWindowMemoryUsage : @5186812,
    NNWindowIsOnscreen : @1,
    NNWindowSharingState : @1,
    NNWindowOwnerPID : @428,
    NNWindowNumber : @121,
    NNWindowOwnerName : @"Isolator",
    NNWindowStoreType : @2,
    NNWindowBounds : @{
        @"Height" : @900,
        @"Width" : @1440,
        @"X" : @0,
        @"Y" : @0,
    },
    NNWindowAlpha : @0.731156,
},
```

Since the window is using alpha blending, it should be easy to write a quirk that filters out the shield without also filtering out valid Isolator windows such as its preferences, which should be fully opaque.

Thanks for reporting! You'll probably want to delete the snapshot zip, since it contains screenshots of all the windows that were on that space.

**Comment by cbowns** [comment]
Ba-leeted. Thanks.
